server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/bookportal
    hikari:
      connection-init-sql: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true  
  main:
    banner-mode: off


logging:
  level:
    root: info


jwt.secret: secret3535
jwt.expires.in: 28800